spring:
  datasource:
    name: ${SPRING_DATASOURCE_NAME:jbcn}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jbcn}?useUnicode=true&amp;characterEncoding=utf-32
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    tomcat:
      max-active: 10
      initial-size: 5
      max-idle: 5
      min-idle: 1
      test-while-idle: true
      test-on-borrow: true
      validation-query: Select 1
      validation-interval: 30
      time-between-eviction-runs-millis: 60000
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    properties.hibernate.connection.useUnicode: true
    properties.hibernate.connection.characterEncoding: utf32
    properties.hibernate.connection.CharSet: utf32
  jackson:
    serialization.write-dates-as-timestamps: false
    deserialization.adjust-dates-to-context-time-zone: false


twitter:
  accessToken: ${TWITTER_ACCESS_TOKEN}
  accessTokenSecret: ${TWITTER_ACCESS_TOKEN_SECRET}
  consumerKey: ${TWITTER_CONSUMER_KEY}
  consumerSecret: ${TWITTER_CONSUMER_SECRET}
  keywords: ${TWITTER_KEYWORDS:jbcn17,barcelonajug,jbcnconf}